### PR TITLE
Make root readonly, create a partition for persistent data

### PR DESCRIPTION
**Pull request by nisargjhaveri**
In an attempt to reduce SD card failures due to power outages when being written:
- Create a new partition and mount it at /persist. Use this partition for things we need to persist like the bluetooth connection info.
- Make root readonly, reducing the chances of unnecessary writes to the sd card.

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
This should help with #138 and #109. This seems to reduce SD card writes. It only writes on boot or when bluetooth is connected. Would be great if more people can try out.

Not sure what else was continuously writing on root though. Logs are anyway on tmpfs. But this looks like a good idea anyway to reduce chances of some service accidentally writing.

**Comment by pavitra14** [comment]
Flashed this today, Let's see how it goes! 
Thanks @nisargjhaveri !

**Comment by BaderSZ** [comment]
While we're at it, could you also make `/var/log` link to `/persist/log`?

Ideally, this would only be the case for 'development' images, but since those aren't released, it should be fine as is. The question is what to do if the partition is full (`BR2_PACKAGE_LOGROTATE`?)

**Comment by nisargjhaveri** [comment]
@BaderSZ having logs writing to sd card will increase the chances of sd card corruption by a large margin. I don't think it is wise to persist logs by default.

Having separate development images is a good idea, or I was maybe thinking of having a config that can enable logs to persist.

**Pull request merged**
